### ISSUE TITLE
vérifier les nb_unit dans les calculs de résultat

### ISSUE THREAD

**Issue by briceandre** [briceandre/BorningChallenge#11]

**Comment by briceandre** [comment]
done

**Comment by OlivierDEVOSAlstom** [comment]
Salut Brice
Je ne sais pas si c'est la bonne action a ré-ouvrir mais il y a un souci dans les calculs.
1) Quand j'encode 25km de VTT je me retrouve avec 16,7 bornes alors que ce devrait être 10 bornes
2) Quand j'encode 40km de vélo je me retrouve avec 16 bornes alors que ce devrait être 10 bornes
3) Quand j'encode 20 km de marche quotidienne je me retrouve avec 6,7 bornes alors que ce devrait être 10 bornes
![Tableau calcul bornes](https://user-images.githubusercontent.com/110242190/184886172-583adc29-1447-4a6c-bc9d-ee50a864f64c.JPG)

**Comment by briceandre** [comment]
J'ai corigé les 3 points ci-dessus. Mais je repasserai de toute façon sur l'ensemble du règlement pour vérifier que les autres sont OK

**Comment by briceandre** [comment]
Juste pour info : ça ne change rien pour les activités déjà encodées. Si tu veux tester, tu dois modifier ton activité, ou en créer une nouvelle

**Comment by OlivierDEVOSAlstom** [comment]
J'ai encore un souci :(
Je suis désolé je n'ai pas vérifier mais les bornes D+ ne sont pas bien comptées 
- Pour le VTT je gagne 1 borne si je fais 150m de dénivelé et non pas 250m
- Pour le vélo je gagne 1 borne si je fais 250m de dénivelé et non pas 400m

**Comment by OlivierDEVOSAlstom** [comment]
Désolé cette fois ci j'ai écris le commentaire et je pensais que ça avait bien réouvert l'action - mais j'avoue ne pas avoir vérifié...

De : briceandre ***@***.***>
Envoyé : mercredi 24 août 2022 08:17
À : briceandre/BorningChallenge ***@***.***>
Cc : DEVOS Olivier ***@***.***>; State change ***@***.***>
Objet : Re: [briceandre/BorningChallenge] vérifier les nb_unit dans les calculs de résultat (Issue #11)

CAUTION: This email was sent from outside Alstom. Be vigilant if you want to click on links or open attachments.

Reopened #11<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbriceandre%2FBorningChallenge%2Fissues%2F11&data=05%7C01%7Colivier.devos-1%40alstomgroup.com%7Cd7c10b04cd904b9d437008da85984084%7C0d993ad3fa73421ab1291fe5590103f3%7C0%7C0%7C637969186210591087%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lux8GLf1xQuxA7SiFCkB8NfI4ugbruenWFWkWbSmZ4w%3D&reserved=0>.

-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbriceandre%2FBorningChallenge%2Fissues%2F11%23event-7247824412&data=05%7C01%7Colivier.devos-1%40alstomgroup.com%7Cd7c10b04cd904b9d437008da85984084%7C0d993ad3fa73421ab1291fe5590103f3%7C0%7C0%7C637969186210591087%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=N5q9Rm%2FBW6FEZVLoAK4uWqgRkZYFagFQWTUOBoRT2KM%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA2JCTDVSC42FIT7EV3W4EUTV2W45TANCNFSM55KDP6TQ&data=05%7C01%7Colivier.devos-1%40alstomgroup.com%7Cd7c10b04cd904b9d437008da85984084%7C0d993ad3fa73421ab1291fe5590103f3%7C0%7C0%7C637969186210591087%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ETQ48nyu7bF5Gig%2BMYD61COJ4LSULINSVIbavMRANoE%3D&reserved=0>.
You are receiving this because you modified the open/close state.Message ID: ***@***.******@***.***>>
In case of strong suspicion of phishing, report the email through the reporting tool on your Outlook toolbar or send it as an attachment to ***@***.******@***.***>

________________________________
CONFIDENTIALITY : This e-mail and any attachments are confidential and may be privileged. If you are not a named recipient, please notify the sender immediately and do not disclose the contents to another person, use it for any purpose or store or copy the information in any medium.

**Comment by briceandre** [comment]
done
